apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
  name: {{.Values.service.serviceName }}
  namespace: {{.Values.namespace.name | default "default"}}
spec:
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name | quote }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

