name: CI/CD Pipeline

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/flask_helloworld:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/flask_helloworld:latest
  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run test
        run: |
          echo "tests are running"
          pytest

  deployment:
    runs-on: 'ubuntu-latest'
    needs: test
    outputs:
      kubeconfig-path: ${{ steps.save-kubeconfig.outputs.kubeconfig-path }}

    steps:

      - uses: actions/checkout@v2

      - name: start minikube
        uses: medyagh/setup-minikube@master
      
      - name: try the cluster !
        run: kubectl get pods -A

      
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      - name: Install Helm chart with value override
        run: |
            helm install hello-world ./hello-world --set image.tag=${{ github.sha }}

      - name: check our deployment
        run: |
          sleep 180
          kubectl get deployments -n helloworld
          kubectl describe deployment hello-world -n helloworld
          